### ISSUE TITLE
I have to fix some things before I was able to compile and run the test sample

### ISSUE THREAD

**Issue by ajsergeev** [polymer-dart/dart2ts#1]
Hi, basically:
1) I have to get rid of Function in dart code, replace it by typedef (I'm using dart SDK 1.22 )
2) I have to add ts libs to tsconfig.json
      "experimentalDecorators" :true,
+	"lib": [      
+      "dom",
+      "es2015",
+      "esnext.asynciterable"
     ]
3) I have to copy dart-sdk (ts) into e2e_test/lib

Very interesting project, thanks!!!

**Comment by ajsergeev** [comment]
[changes.txt](https://github.com/polymer-dart/dart2ts/files/1502016/changes.txt)

**Comment by ajsergeev** [comment]
With analizer I was able to make it work only like this:
typedef dynamic FLATTER_WITH_DT(Y);
Iterable<X> flattenWith<X, Y>(Iterable<Y> x, FLATTER_WITH_DT extract) sync* {
and
X runWithContext<X>(AnalysisContext ctx, Function body) => runZoned(() => body() as X, zoneValues: {'dart2ts.analysisContext':ctx});

**Comment by dam0vm3nt** [comment]
Thanks. Yes `Function` style is not yet supported. Now I'm a bit stuck because I had to find a convenient way to support the core lib.

**Comment by dam0vm3nt** [comment]
please can you send me a PR for the changes you submitted ? I will definitively try to merge them.

**Comment by ajsergeev** [comment]
Hi, 
could you, please, allow me to push a branch so I can push my changes and do Pull-Request? Then you will be able to filter-out what you need and merge changes.
Thanks!

**Comment by dam0vm3nt** [comment]
You just have to fork the repo. Push your changes on your own fork then use GitHub to create and send me the push request. That's how usually works with GitHub projects

**Comment by ajsergeev** [comment]
Done

**Comment by dam0vm3nt** [comment]
Merged. I've changed one thing where you patched the code for windows, but could not test it if it doesn't break. Can you check it for me please ? Tnx again!

**Comment by ajsergeev** [comment]
Hi, tested, now all imports are broken for me because they all use platform separator ('\'):
1) sample1.dart has imports:
import 'sample2.dart' as xy;
import 'package:js/js.dart';
import 'sample3.dart';
import 'dart:html';
import 'model/model.dart' as DGM;  // just lib in nested folder with simple classes
2) When compiled to ts, I've got in sample1.ts
import * as lib1 from ".\sample3";
import * as lib2 from ".\sample2";
import * as core from "dart_sdk/core";
import * as lib4 from ".\model\model";
3) When running webpack I've got a message it can't find that files. This is working fine:
import * as lib1 from "./sample3";
import * as lib2 from "./sample2";
import * as core from "dart_sdk/core";
import * as lib4 from "./model/model";
Let me know if you need more info, I'll make a short video that demonstraits the issue.
Thanks!

**Comment by dam0vm3nt** [comment]
ouch! Ok, I've restored your path separator replacement trick, can you test it now ?

**Comment by ajsergeev** [comment]
It works good now for me. Thanks!
